name: karmayogi_mobile
description: It enables individual officials to recognize competency gaps and close them.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.7.10+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.0
  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.4
  # This package allows to use Google Fonts in the app.
  google_fonts: ^2.3.3
  # This  package display information to the user using a custom layout, that can be actionable.
  big_tip: ^3.0.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.0.2
  # The following adds Simple Equality Comparisons to your application.
  equatable: ^2.0.0
  # Flutter Secure Storage provides API to store data in secure storage.
  flutter_secure_storage: ^5.1.2
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^1.1.6
  # Generate image provider from svg path, use flutter_svg as a dependency.
  flutter_svg_provider: ^1.0.3
  # A simple implementation of the Moment.js features for relative time.
  simple_moment: ^1.0.7
  # This is a simple widget that allows your users to create tags by entering the tag's name inside of textfield and make the tags appear in the textfield.
  textfield_tags: ^2.0.0
  # Pre built animations for flutter
  animations: ^2.0.0
  # A library that exposes device specific speech recognition capability.
  speech_to_text: ^5.6.1
  # Library to launch a url in flutter mobile applications
  url_launcher: ^6.1.7
  # A SQLite database is a file in the file system identified by a path.
  sqflite: ^2.0.0+3
  # A comprehensive, cross-platform path manipulation library for Dart.
  path: ^1.8.2
  # Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0
  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.8.5
  # A Flutter plugin for Android and iOS supports cropping images.
  image_cropper: ^1.3.1
  # An autocomplete textfield for flutter
  autocomplete_textfield: ^1.7.3
  # Flutter tags let you create clickable tags or create new ones using textField, adapting perfectly to the width of the screen.
  flutter_tags: ^0.4.9+1
  # A flutter plugin for handling PDF files. Works on both Android & iOS.
  advance_pdf_viewer:
    git:
      url: https://github.com/ncdm-stldr/pdf_viewer.git
  # The video_player plugin provides low-level access to video playback.
  chewie: ^1.3.6
  # A Flutter plugin for iOS, Android and Web for playing back video on a Widget surface.
  video_player: ^2.5.0
  # Rive is a real-time interactive design and animation tool.
  rive: ^0.8.4
  # A Flutter package for building Flutter widget tree from HTML with support for IFRAME, VIDEO and 70+ other tags.
  flutter_widget_from_html: ^0.8.5
  # A Flutter plugin that provides a WebView widget.
  webview_flutter: ^3.0.4
  # A Flutter flugin that provides a socket connection
  socket_io_client: ^1.0.2
  # To decode jwt token
  jwt_decoder: ^2.0.1
  # To create animated splash screen in a fully customizable way.
  animated_splash_screen: ^1.2.0
  # #Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^9.2.0
  #A pdf producer for Dart. It can create pdf files for both web or flutter.
  pdf: ^3.8.4
  #Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).

  # Drag And Drop gives you the freedom of creating a reorder the GridViewItems simple by Drag And Drop.
  reorderables:
    ^0.4.1
    # A Flutter plugin to get the ANDROID_ID for android and identifierForVendor for iOS platforms.
  unique_identifier: ^0.2.2
  #enables images to become able to zoom and pan with user gestures such as pinch, rotate and drag.
  photo_view: ^0.13.0
  #Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS
  share_plus: ^4.5.3
  #Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.0.10
  #A plugin that provides you with intermediate PDF rendering APIs and easy-to-use Flutter Widgets.
  pdf_render: ^1.3.6
  #Provides server and web apps the ability to load, manipulate, and save images with various image file formats including PNG, JPEG, GIF, BMP, WebP, TIFF, TGA, PSD, PVR, and OpenEXR.
  image: ^3.3.0
  #Introduction/Onboarding package for flutter app with some customizations possibilities
  introduction_screen: ^3.1.4
  #A pure Dart library that checks for internet by opening a socket to a list of specified addresses, each with individual port and timeout. Defaults are provided for convenience.
  internet_connection_checker: 0.0.1+3
  #Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^2.3.9
  #Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^1.24.0
  #Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  firebase_messaging: ^11.4.4
  #A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customize for each platform.
  flutter_local_notifications: ^9.2.0
  envied: ^0.2.4
  #A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
  open_file_safe: ^3.2.3
  upgrader: ^4.8.1
  app_links: ^3.4.1
  clippy_flutter: ^1.1.1
  youtube_player_iframe: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  charts_common: ^0.12.0
  charts_flutter: ^0.12.0
  flutter_launcher_icons: ^0.9.0
  envied_generator: ^0.2.3+1
  build_runner: ^2.3.2

# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/smileys/
    - assets/animations/
    - assets/html/
    - assets/launcher_icons/

flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/launcher_icons/android_launcher_icon.png"
  image_path_ios: "assets/launcher_icons/ios_launcher_icon.png"
  remove_alpha_ios: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
